import type { GridPos } from '@game/schema';

/** Browser-safe deterministic encounter facts shared by the CLI harness and sandbox. */
export const cryptScenario = {
  id: 'crypt-solo-v1',
  seed: 2901,
  pc: {
    id: 'pc-aria',
    team: 'pc',
    kind: 'pc' as const,
    pos: { x: 9, y: 4 } satisfies GridPos,
    size: 1,
    hp: 10,
    maxHp: 10,
    ac: 12,
    speed: 30,
    abilities: { str: 10, dex: 14, con: 14, int: 16, wis: 10, cha: 10 },
    attackBonus: 4,
    damage: '1d6+2',
  },
  goblins: [
    {
      id: 'goblin-1',
      team: 'goblin',
      kind: 'monster' as const,
      pos: { x: 8, y: 4 } satisfies GridPos,
      size: 1,
      hp: 4,
      maxHp: 4,
      ac: 15,
      speed: 30,
      abilities: { str: 10, dex: 15, con: 10, int: 10, wis: 10, cha: 10 },
      attackBonus: 4,
      damage: '1d6+2',
    },
    {
      id: 'goblin-2',
      team: 'goblin',
      kind: 'monster' as const,
      pos: { x: 10, y: 4 } satisfies GridPos,
      size: 1,
      hp: 4,
      maxHp: 4,
      ac: 15,
      speed: 30,
      abilities: { str: 10, dex: 15, con: 10, int: 10, wis: 10, cha: 10 },
      attackBonus: 4,
      damage: '1d6+2',
    },
  ],
  movePath: [
    { x: 9, y: 4 },
    { x: 9, y: 3 },
    { x: 9, y: 2 },
  ] satisfies GridPos[],
  areaAnchor: { x: 9, y: 2 } satisfies GridPos,
  areaDirection: { x: 0, y: 1 } satisfies GridPos,
  spellId: 'spell:burning-hands',
} as const;
